name: flutter_esc_pos_utils
description: This package is used to generate ESC/pos commands to print using Bluetooth, WiFi/Network, or USB printers.
version: 1.0.1
homepage: https://github.com/mjafartp/flutter_esc_pos_utils

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  gbk_codec: ^0.4.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - packages/flutter_esc_pos_utils/resources/capabilities.json
